#!/usr/bin/env bash
# One-shot installer for Raspberry Pi OS (Bookworm, Pi 4) — works on the
# *Lite* (no desktop) image as well as the full desktop.
#
#   ./install.sh                # install + enable autostart on boot
#   ./install.sh --no-autostart # install only, don't touch systemd
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"
TARGET_USER="${SUDO_USER:-$USER}"
AUTOSTART=1
[ "${1:-}" = "--no-autostart" ] && AUTOSTART=0

cd "$REPO"

echo ">> Installing system packages..."
sudo apt-get update
# python3-pygame from apt is linked against the system SDL2, which on Pi OS is
# built with the KMSDRM driver — that's what renders fullscreen with no desktop.
# The Mesa GL/EGL/DRI packages are NOT on Pi OS Lite by default, but SDL's
# kmsdrm backend renders through EGL — without them you get "egl not initialized".
sudo apt-get install -y \
    python3-pygame python3-lgpio python3-gpiozero \
    libgl1-mesa-dri libegl1 libegl-mesa0 libgles2

echo ">> Creating venv (reusing the apt-installed pygame/gpiozero)..."
python3 -m venv --system-site-packages .venv

echo ">> Adding $TARGET_USER to the video/render/input/gpio groups..."
sudo usermod -aG video,render,input,gpio "$TARGET_USER" || true

if [ "$AUTOSTART" = "1" ]; then
    echo ">> Installing systemd service for $TARGET_USER (autostart on boot)..."
    sudo tee /etc/systemd/system/grand-prix.service >/dev/null <<EOF
# Generated by install.sh — pinewood derby, fullscreen on boot via KMSDRM (tty1).
[Unit]
Description=Grand Prix RPi pinewood derby
After=multi-user.target
Conflicts=getty@tty1.service
OnSuccess=getty@tty1.service

[Service]
User=$TARGET_USER
SupplementaryGroups=video render input tty gpio
WorkingDirectory=$REPO
Environment=SDL_VIDEODRIVER=kmsdrm
Environment=SDL_AUDIODRIVER=dummy
TTYPath=/dev/tty1
StandardInput=tty
StandardOutput=tty
ExecStart=$REPO/.venv/bin/python $REPO/main.py
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
    sudo systemctl daemon-reload
    sudo systemctl enable grand-prix.service
    echo ">> Enabled. It will start on every boot."
    echo "   Start now:   sudo systemctl start grand-prix.service"
    echo "   Stop:        sudo systemctl stop grand-prix.service"
    echo "   Disable:     sudo systemctl disable grand-prix.service"
    echo "   Logs:        journalctl -u grand-prix.service -b"
fi

echo
echo ">> Done.  (Log out/in once so the new groups take effect.)"
echo "Run by hand on the console:   .venv/bin/python main.py"
echo "Dev in a window with mock:    .venv/bin/python main.py --windowed --mock"
echo "Check the display driver:"
echo "    .venv/bin/python -c \"import pygame; pygame.display.init(); print(pygame.display.get_driver())\""
